### ISSUE TITLE
Style Linking Issues

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gf-glyphs-scripts#37]
Is there a recommendations guide on style linking?

I ran the QA script in gf-glyphs-scripts and I'm getting a few errors I don't understand (my setup currently is that I have 1 set of instances for OTF, and 1 set for Webfonts with different vertical metric schemes, I also have a set for Italics, with the same vertical metrics as the TTF).

Firstly I had every italic instance linked to its upright counterpart, then I had "Bold" linked as Bold then "Bold Italic" as the Bold-Italic of Regular, I got these issues:

```
================================================================================
FAIL: Check style linking is correct for italic instances
--------------------------------------------------------------------------------
Italic instance must have no style linking.
Delete link to Regular

================================================================================
FAIL: Check style linking is correct for non italic instances
--------------------------------------------------------------------------------
Bold instance must have no style linking. Delete link to Regular
```

So I remove the linking in the "Italic" instance (why is that the case that every other weight should have Italic linking but not the 400 Regular Italic [named "Italic"]?)

Then I remove the style linking in the "Bold" instances. But keep the linking in the "Bold Italic" (this seems inconsistent). Now I get more issues:

```
================================================================================
FAIL: Check only Bold and Bold Italic have 'isBold' set
--------------------------------------------------------------------------------
'Bold' instance is a Bold weight.
Enable "Bold of" for this instance.

================================================================================
FAIL: Check only italic instances have 'isItalic' set
--------------------------------------------------------------------------------
'Italic' instance is an Italic.
Enable 'Italic of' for the instance

================================================================================
FAIL: Check style linking is correct for italic instances
--------------------------------------------------------------------------------
Italic instance must have no style linking.
Delete link to None

================================================================================
FAIL: Check style linking is correct for non italic instances
--------------------------------------------------------------------------------
Bold instance must have no style linking. Delete link to None
```

Confusingly, now the script is returning that in fact the "Bold" instance should be enabled as Bold (of Regular?), same with "Italic" as Italic. While at the same time returning Italic must have no style linking?

I have run the script on [this file](https://github.com/weiweihuanghuang/Work-Sans/raw/cb88fe3db077c71e01678deb8389217646b57565/sources/Work%20Sans.glyphs)

**Comment by weiweihuanghuang** [comment]
Also it reports the "Thin Italic" instance as missing custom parameters:
```

================================================================================
FAIL: Check family has vertical metric custom parameters
--------------------------------------------------------------------------------
Thin Italic master is missing the following vertical metric custom parameters [typoAscender, winAscent, typoLineGap, hheaLineGap, hheaAscender, hheaDescender, typoDescender, winDescent]
```
When they are in the file.

**Comment by m4rc1e** [comment]
- The vertical metric customParams should be applied to the masters, not the instances.
- Script looks at all masters/instances. Apply linkStyles to hidden instances.
- Issue with linkedStyle has been fixed, #39. Will merge this later

I'm  attaching a fixed version of your source, please diff them to see what I've changed.


[Work_Sans.glyphs.zip](https://github.com/googlefonts/gf-glyphs-scripts/files/2552256/Work_Sans.glyphs.zip)

**Comment by weiweihuanghuang** [comment]
Thanks Marc I tried the script from https://github.com/googlefonts/gf-glyphs-scripts/pull/39
I still get this on your .glyphs file:
```
================================================================================
FAIL: Check style linking is correct for non italic instances
--------------------------------------------------------------------------------
Bold instance must have no style linking. Delete link to None
```

**Comment by m4rc1e** [comment]
If I download the zip and run the QA script, I get the following:

```
================================================================================
TESTS RUN: 26 | PASSED: 21 | FAILED: 5
================================================================================


================================================================================
FAIL: Check 'AUTHORS.txt' exists
--------------------------------------------------------------------------------
'AUTHORS.txt' is missing in parent directory.

Use https://raw.githubusercontent.com/Gue3bara/Cairo/master/AUTHORS.txt as a reference to make your own.


================================================================================
FAIL: Check 'CONTRIBUTORS.txt' exists
--------------------------------------------------------------------------------
'CONTRIBUTORS.txt' is missing in parent directory.

Use https://raw.githubusercontent.com/Gue3bara/Cairo/master/CONTRIBUTORS.txt as a reference to make your own.


================================================================================
FAIL: Check 'fonts' directory exists
--------------------------------------------------------------------------------
'/Users/marc/fonts' folder is missing or named incorrectly.

Font binaries should be generated into this folder. Sub folders for 'ttf', 'otf', 'web' are allowed.


================================================================================
FAIL: Check OFL.txt first line matches the copyright string
--------------------------------------------------------------------------------
OFL.txt and font copyright do not match.

OFL copyright: Copyright 2018 The Work Sans Project Authors (https://github.com/weiweihuanghuang/Work-Sans), with Reserved Font Name "Work Sans".
Font copyright: Copyright 2018 The Work Sans Project Authors (https://github.com/weiweihuanghuang/Work-Sans), with Reserved Font Name "(Work Sans)".



================================================================================
FAIL: Check 'sources' directory exists
--------------------------------------------------------------------------------
'/Users/marc/sources' folder is missing or named incorrectly.

Source files must be stored here. There should only be one definitive source. Version control allows us to access previous version (we can rewind history if needed).

Naming files using the following convention is banned, family-regular_AA|AB.ttf.

```

Which commit are you using?

You should be using 275cd531aff1e66dab11ff3f3ab0c3cfda02a5c6, if not repull

**Comment by weiweihuanghuang** [comment]
Oops my bad you're right, everything is good now
